#!/usr/bin/env bash

#inst-k3s-client V1.0
#Author: RH363
#Date: 10/01/2024

ROOT_UID=0                                                                                                   
USER_UID=$(id -u)                                                                                            
ERR_NOTROOT=86
ERR_INV_OPTION=94


# Regular Colors
Color_Off='\033[0m'       # Text Reset

Red='\033[0;31m'          # Red
Blue='\033[0;34m'         # Blue

server=""
token=""

usage() {
 echo "Usage: $0 [OPTIONS]"
 echo "Colors:"
 echo -e "${Red} ERROR" 
 echo -e "${Blue} INFO ${Color_Off}"
 echo "Options:"
 echo " -h, --help            Display this help message"
 echo " -s, --server          SERVER(REQUIRED) Define master server ip or hostname"
 echo " -t, --token           TOKEN(REQUIRED) Define master token located in /var/lib/rancher/k3s/server/node-token on your master node"
}

while (($# > 0)); do
    case "$1" in
        "-h"|"--help")
            usage
            exit
        ;;
        "-s"|"--server")
            if [ -z "$2" ];then
                echo -e "${Red}SERVER OPTION REQUIRE AN ARGUMENT${Color_Off}"
                exit $ERR_INV_OPTION
            fi
            server=$2
            shift 2
        ;;
        "-t"|"--token")
            if [ -z "$2" ];then
                echo -e "${Red}TOKEN OPTION REQUIRE AN ARGUMENT${Color_Off}"
                exit $ERR_INV_OPTION
            fi
            token=$2
            shift 2
        ;;
        *)
            echo -e "${Red}INVALID OPTION: $1${Color_Off}"
            exit $ERR_INV_OPTION
        ;;
    esac
done

if [ "$USER_UID" -ne "$ROOT_UID" ]                                                                           
    then
    echo -e "${Red}MUST BE ROOT TO RUN THIS SCRIPT${Color_Off}"
    exit $ERR_NOTROOT
    fi

if [ "$server" = " " ] || [ "$token" = " " ];then
    echo -e "${Red}CANT INSTALL K3S: SERVER AND TOKEN PARAMETER ARE REQUIRED${Color_Off}"
    exit $ERR_INV_OPTION
    
fi


case "$(lsb_release -is)" in
    "Ubuntu"|"Debian")
        echo -e "${Blue}UBUNTU,DEBIAN ENVIROMENT DETECTED"
        echo -e "${Blue}UPGRADE SYSTEM${Color_Off}"
        apt update && apt upgrade -y
        echo -e "${Blue}INSTALL CURL${Color_Off}"
        apt install curl -y
        echo -e "${Blue}INSTALL OPEN-ISCSID${Color_Off}"
        apt-get install open-iscsi -y
        modprobe iscsi_tcp
        systemctl enable --now iscsid
        systemctl restart iscsid
        echo -e "${Blue}INSTALL NFS-COMMON${Color_Off}"
        apt-get install nfs-common -y

        curl -sfL https://get.k3s.io | K3S_URL=https://$server:6443 K3S_TOKEN=$token sh -
    ;;
    *)
        echo -e "${Red}DISTRO NOT YET SUPPORTED${Color_Off}"
    ;;
esac